Needs more beans
mattbarrio/sam-loves-beans pull request #2
Opened 2022-11-29 19:51 UTC by jminyardjc

Added more beans

2022-11-29 19:55 UTC, sam11385 requested changes
Delete line

2022-11-29 19:58 UTC, sam11385 requested changes
remove template

2022-11-29 20:32 UTC, jminyardjc commented
@mattbarrio  you get to decide. 😄

2022-11-29 22:54 UTC, ddouglassjc commented
Most perfect PR I've ever seen.

2022-11-30 20:40 UTC, mattbarrio reviewed
A slight adjustment on the script to open a new window. 

More tabs with more beans == winning

2022-11-30 20:40 UTC, mattbarrio commented on templates/header.tmpl
> +        Click this <span id="magic">magic bean</span> to experience the greatness of BEANS! »»»<button id="magic-beans" class="button padding-large white border" onclick="window.location.href='https:
```suggestion
        Click this <span id="magic">magic bean</span> to experience the greatness of BEANS! »»»<button id="magic-beans" class="button padding-large white border" onclick="window.open('https://www.youtube.com/watch?v=wEEuzUGEWws','_blank')"><img src="/static/img/logo.png"></button>«««</span>
```

2022-12-01 01:11 UTC, merged